Initial commit with 24 Actions added.
fortinet-fortisoar/connector-netbox pull request #1
Opened 2024-01-03 07:25 UTC by cs-adarsh-gupta

### Descriptions:
 
#### PMDB : 28727
 
#### UTCs: 
 
- [x] Connector installation verified. 
- [x] Connector logo verified. 
- [x] Actions and Playbook list verified. 
- [x] Playbook tags verified. 
- [x] All Playbook are in info mode verified. 
- [x] All Playbook are in inactive mode verified.

2024-01-03 09:57 UTC, cs-sameer-pathan requested changes

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/info.json
> +            "dns_name": "*.G7tafc4lbh4wzM6rk8u4RVrwSZQjKHUkopm6odkzY7ao3A5D6ZBtPlhdsXOVwGSq3H9vuWbb.D5EWQI0yFjpnkXiBKJpSObjpNovFX8-.F4VlX_dXq0QVuGYb6vCfdm.fn8ByqgCQBiD44X2qBoT6bQ_0ziYqaTedzFD4UK9lxhr
Please remove this example or keep keys only with empty values.
Provide actual example in sample playbook

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/info.json
> +          "title": "Other Fields",
Please add important parameters like id , status, filter etc. if possible in other actions as well

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/operations.py
> +        if not self.server_url.startswith('https://'):
Please check for http or https

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/operations.py
> +        self.server_url.strip('/')
need to assign this value to self.server_url

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/operations.py
> +            # # CURL UTILS CODE
why commented this section ?

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/operations.py
> +                if method == 'delete':
Please check case of the string 'delete' or check with method.lower() == 'delete'

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/operations.py
> +        response = tg.make_request(endpoint=endpoint)
if possible provide limit parameter . No need to fetch more data for health check

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/playbooks/playbooks.json
> +        "Netbox",
change this tag to NetBox for all occurrences.

2024-01-03 09:57 UTC, cs-sameer-pathan commented on netbox/playbooks/playbooks.json
> +                "config": "''",
```suggestion
                "config": "",
```

2024-01-04 05:26 UTC, cs-adarsh-gupta commented
Resolved comments

2024-01-19 17:49 UTC, cs-prerna-joshi approved these changes
LGTM

2024-01-19 17:50 UTC, merged